import { NextResponse } from "next/server";
import { z } from "zod";
import { connectDB } from "@/lib/mongodb";
import { readCustomerId } from "@/lib/customerAuth";
import Cart from "@/models/Cart";
import Product from "@/models/Product";
import { objectId, priceFor, validVariants } from "@/lib/commerce";
const addSchema = z.object({ productId: z.string(), quantity: z.number().int().positive().max(100000), selectedVariants: z.array(z.object({ name: z.string().trim().min(1).max(80), value: z.string().trim().min(1).max(120) })).max(20).default([]) });
const serialize = (cart) => ({ id: cart.id, items: cart.items.map((item) => ({ id: item.id, product: item.product && { id: item.product.id, title: item.product.title, slug: item.product.slug, image: item.product.image, stock: item.product.stock, priceTiers: item.product.priceTiers }, quantity: item.quantity, selectedVariants: item.selectedVariants, priceAtAddTime: item.priceAtAddTime })) });
async function ownedCart(id) { return Cart.findOne({ customer: id }).populate("items.product", "title slug image stock priceTiers minimumOrderQuantity variants"); }
export async function GET() { const customer = readCustomerId(); if (!customer) return NextResponse.json({ error: "Please sign in to use your cart." }, { status: 401 }); await connectDB(); const cart = await ownedCart(customer); return NextResponse.json({ cart: cart ? serialize(cart) : { items: [] } }); }
export async function POST(request) { const customer = readCustomerId(); if (!customer) return NextResponse.json({ error: "Please sign in to add products." }, { status: 401 }); try { const input = addSchema.parse(await request.json()); if (!objectId(input.productId)) throw new Error("Invalid product"); await connectDB(); const product = await Product.findById(input.productId); if (!product || product.stock < input.quantity || input.quantity < product.minimumOrderQuantity || !validVariants(product, input.selectedVariants)) return NextResponse.json({ error: "This product configuration is unavailable." }, { status: 400 }); const price = priceFor(product, input.quantity); if (price === null) return NextResponse.json({ error: "A valid price tier was not found." }, { status: 400 }); let cart = await Cart.findOne({ customer }); const matching = cart?.items.find((item) => item.product.toString() === product.id && JSON.stringify(item.selectedVariants) === JSON.stringify(input.selectedVariants)); if (!cart) cart = new Cart({ customer, items: [] }); if (matching) { const quantity = matching.quantity + input.quantity; if (quantity > product.stock) return NextResponse.json({ error: "Requested quantity exceeds available stock." }, { status: 400 }); matching.quantity = quantity; matching.priceAtAddTime = priceFor(product, quantity); } else cart.items.push({ product: product._id, quantity: input.quantity, selectedVariants: input.selectedVariants, priceAtAddTime: price }); await cart.save(); cart = await ownedCart(customer); return NextResponse.json({ cart: serialize(cart) }, { status: 201 }); } catch { return NextResponse.json({ error: "Please check the product and quantity." }, { status: 400 }); } }
export async function DELETE() { const customer = readCustomerId(); if (!customer) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); await connectDB(); await Cart.updateOne({ customer }, { $set: { items: [] } }); return NextResponse.json({ cart: { items: [] } }); }
