"use client";
import { useEffect, useState } from "react";

export default function ProductReviews({ slug }) {
  const [data, setData] = useState(null); const [rating, setRating] = useState(5); const [comment, setComment] = useState(""); const [status, setStatus] = useState("");
  const load = () => fetch(`/api/products/${slug}/reviews?limit=8`).then((r) => r.json()).then(setData).catch(() => setData({ reviews: [], total: 0, average: 0 }));
  useEffect(load, [slug]);
  const submit = async (event) => { event.preventDefault(); const response = await fetch(`/api/products/${slug}/reviews`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rating, comment }) }); const result = await response.json(); setStatus(response.ok ? "Thanks — your review is awaiting approval." : result.error || "Unable to submit review."); if (response.ok) { setComment(""); load(); } };
  if (!data) return <section className="mt-12"><p className="text-sm text-ink/50">Loading reviews…</p></section>;
  return <section className="mt-12 border-t border-ink/10 pt-8"><h2 className="font-heading text-2xl font-semibold">Customer reviews</h2><p className="mt-2 text-sm text-ink/65">{data.total ? `${data.average.toFixed(1)} / 5 from ${data.total} review${data.total === 1 ? "" : "s"}` : "No approved reviews yet."}</p><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_20rem]"><div className="space-y-4">{data.reviews.map((review) => <article key={review._id} className="rounded-card bg-surface-muted p-4"><p className="font-medium">{"★".repeat(review.rating)}<span className="text-ink/25">{"★".repeat(5 - review.rating)}</span> <span className="ml-2 text-sm text-ink/60">{review.customerName}</span></p><p className="mt-2 whitespace-pre-wrap text-sm text-ink/75">{review.comment}</p></article>)}</div><form onSubmit={submit} className="h-fit rounded-card border border-ink/10 p-4"><h3 className="font-heading font-semibold">Write a review</h3><label className="mt-3 block text-sm">Rating<select value={rating} onChange={(e) => setRating(Number(e.target.value))} className="mt-1 w-full rounded border border-ink/20 p-2">{[5,4,3,2,1].map((item) => <option key={item} value={item}>{item} star{item > 1 ? "s" : ""}</option>)}</select></label><label className="mt-3 block text-sm">Comment<textarea required minLength="3" maxLength="1500" value={comment} onChange={(e) => setComment(e.target.value)} className="mt-1 w-full rounded border border-ink/20 p-2" rows="4" /></label><button className="btn-primary mt-3 w-full text-sm">Submit review</button>{status && <p role="status" className="mt-3 text-xs text-ink/65">{status}</p>}</form></div></section>;
}
