import { NextResponse } from "next/server";
import { z } from "zod";
import { connectDB } from "@/lib/mongodb";
import { readCustomerId } from "@/lib/customerAuth";
import Product from "@/models/Product";
import Customer from "@/models/Customer";
import Review from "@/models/Review";
const schema = z.object({ rating: z.number().int().min(1).max(5), comment: z.string().trim().min(3).max(1500) });
export async function GET(request, { params }) { await connectDB(); const product = await Product.findOne({ slug: params.slug }).select("_id"); if (!product) return NextResponse.json({ error: "Product not found." }, { status: 404 }); const page = Math.max(1, Number(new URL(request.url).searchParams.get("page")) || 1); const limit = Math.min(20, Math.max(1, Number(new URL(request.url).searchParams.get("limit")) || 8)); const filter = { product: product._id, isApproved: true }; const [reviews, stats] = await Promise.all([Review.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).select("customerName rating comment createdAt").lean(), Review.aggregate([{ $match: filter }, { $group: { _id: "$rating", count: { $sum: 1 } } }])]); const total = stats.reduce((sum, stat) => sum + stat.count, 0); const average = total ? stats.reduce((sum, stat) => sum + stat._id * stat.count, 0) / total : 0; return NextResponse.json({ reviews, total, average, breakdown: Object.fromEntries(stats.map((stat) => [stat._id, stat.count])), hasMore: page * limit < total }); }
export async function POST(request, { params }) { const customerId = readCustomerId(); if (!customerId) return NextResponse.json({ error: "Please sign in to write a review." }, { status: 401 }); try { const input = schema.parse(await request.json()); await connectDB(); const [product, customer] = await Promise.all([Product.findOne({ slug: params.slug }).select("_id"), Customer.findById(customerId).select("name")]); if (!product || !customer) return NextResponse.json({ error: "Product not found." }, { status: 404 }); const review = await Review.findOneAndUpdate({ product: product._id, customer: customerId }, { $set: { customerName: customer.name, rating: input.rating, comment: input.comment, isApproved: false } }, { new: true, upsert: true, setDefaultsOnInsert: true }); return NextResponse.json({ review: { id: review.id, isApproved: review.isApproved } }, { status: 201 }); } catch { return NextResponse.json({ error: "Please provide a rating and a valid comment." }, { status: 400 }); } }
