import { NextResponse } from "next/server";
import { z } from "zod";
import mongoose from "mongoose";
import { connectDB } from "@/lib/mongodb";
import Customer from "@/models/Customer";
import { clearCustomerCookie, readCustomerSession } from "@/lib/customerAuth";
import { activeOtherSession, revokeCustomerSession, touchCustomerSession } from "@/lib/customerSessions";
const address = z.object({ id: z.string().optional(), label: z.string().trim().max(50).optional().default(""), address: z.string().trim().min(5).max(250), city: z.string().trim().min(2).max(80), state: z.string().trim().min(2).max(80), postalCode: z.string().trim().min(3).max(20), country: z.string().trim().min(2).max(80) });
const updateSchema = z.object({ name: z.string().trim().min(2).max(100), phone: z.string().trim().max(30).optional().default(""), addresses: z.array(address).max(10).default([]) });
const safeCustomer = (customer) => customer ? { id: customer.id, name: customer.name, email: customer.email, phone: customer.phone || "", addresses: (customer.addresses || []).map((item) => ({ id: item.id, label: item.label || "", address: item.address, city: item.city, state: item.state, postalCode: item.postalCode, country: item.country })) } : null;
export async function GET() { const session = readCustomerSession(); if (!session) return NextResponse.json({ customer: null }); try { await connectDB(); await touchCustomerSession(session.sessionId); const customer = await Customer.findById(session.id).select("name email phone addresses"); const otherSession = customer ? await activeOtherSession(session.id, session.sessionId) : null; return NextResponse.json({ customer: safeCustomer(customer), otherSession }); } catch { return NextResponse.json({ error: "Unable to load account." }, { status: 500 }); } }
export async function PATCH(request) { const id = readCustomerId(); if (!id) return NextResponse.json({ error: "Please sign in to update your account." }, { status: 401 }); try { const input = updateSchema.parse(await request.json()); await connectDB(); const addresses = input.addresses.map((item) => ({ ...(item.id && mongoose.isValidObjectId(item.id) ? { _id: item.id } : {}), label: item.label, address: item.address, city: item.city, state: item.state, postalCode: item.postalCode, country: item.country })); const customer = await Customer.findByIdAndUpdate(id, { $set: { name: input.name, phone: input.phone, addresses } }, { new: true, runValidators: true }).select("name email phone addresses"); return customer ? NextResponse.json({ customer: safeCustomer(customer) }) : NextResponse.json({ error: "Account not found." }, { status: 404 }); } catch { return NextResponse.json({ error: "Please check your profile and address details." }, { status: 400 }); } }
export async function DELETE() { const session = readCustomerSession(); if (session?.sessionId) { try { await connectDB(); await revokeCustomerSession(session.sessionId); } catch {} } const response = NextResponse.json({ ok: true }); response.cookies.set(clearCustomerCookie()); return response; }
